-- Production Plan schema objects (Firebird)
-- Execute once in target DB before creating client methods.

-- 1) Table for production batches
CREATE TABLE VK_PROD_BATCHES (
  ID BIGINT NOT NULL,
  BATCHNUMBER VARCHAR(120) NOT NULL,
  BATCHTYPE SMALLINT NOT NULL,
  SORTORDER INTEGER NOT NULL,
  DATE_START DATE,
  DATE_END DATE,
  CONSTRAINT PK_VK_PROD_BATCHES PRIMARY KEY (ID),
  CONSTRAINT UQ_VK_PROD_BATCHES_TYPE_NUM UNIQUE (BATCHTYPE, BATCHNUMBER),
  CONSTRAINT CHK_VK_PROD_BATCHES_TYPE CHECK (BATCHTYPE IN (1, 2))
);

-- 2) Generator for IDs (used by addBatch.pas)
CREATE GENERATOR GEN_VK_PROD_BATCHES_ID;
SET GENERATOR GEN_VK_PROD_BATCHES_ID TO 0;

-- 3) Index for fast read in getBatches (by mode + visual order)
CREATE INDEX IDX_VK_PROD_BATCHES_TYPE_SORT ON VK_PROD_BATCHES (BATCHTYPE, SORTORDER);

-- 4) Centralized settings (UF IDs for carp/paint modes)
CREATE TABLE VK_PROD_SETTINGS (
  ID SMALLINT NOT NULL,
  CARP_UF_ID INTEGER NOT NULL,
  PAINT_UF_ID INTEGER NOT NULL,
  CONSTRAINT PK_VK_PROD_SETTINGS PRIMARY KEY (ID),
  CONSTRAINT CHK_VK_PROD_SETTINGS_ID CHECK (ID = 1)
);

INSERT INTO VK_PROD_SETTINGS (ID, CARP_UF_ID, PAINT_UF_ID)
VALUES (1, 170, 171);
